name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Run the workflow only when changes are pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for testing
      - name: Build test Docker image
        run: docker build -t developpex/react-test -f ./client/Dockerfile.dev ./client

      # Run tests
      - name: Run tests
        run: docker run -e CI=true developpex/react-test npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test # This job runs only if the 'test' job completes successfully

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push production images to Docker Hub
      - name: Build and push Docker images
        env:
          DOCKER_REPO: developpex # Replace with your Docker Hub username
        run: |
          docker build -t $DOCKER_REPO/multi-client ./client
          docker build -t $DOCKER_REPO/multi-nginx ./nginx
          docker build -t $DOCKER_REPO/multi-server ./server
          docker build -t $DOCKER_REPO/multi-worker ./worker
          docker push $DOCKER_REPO/multi-client
          docker push $DOCKER_REPO/multi-nginx
          docker push $DOCKER_REPO/multi-server
          docker push $DOCKER_REPO/multi-worker 
